package com.revature.repository.jdbc;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Objects;

/** Owns JDBC connection creation and applies ordered schema migrations. */
public final class JdbcDatabase {
    public static final int CURRENT_SCHEMA_VERSION = 1;

    private final String url;
    private final String username;
    private final String password;

    public JdbcDatabase(String url) {
        this(url, "sa", "");
    }

    public JdbcDatabase(String url, String username, String password) {
        this.url = requireText(url, "url");
        this.username = Objects.requireNonNull(username, "username");
        this.password = Objects.requireNonNull(password, "password");
    }

    public static JdbcDatabase inMemory(String name) {
        return new JdbcDatabase("jdbc:h2:mem:" + requireText(name, "name")
                + ";DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE");
    }

    public Connection openConnection() throws SQLException {
        return DriverManager.getConnection(url, username, password);
    }

    public void migrate() {
        try (Connection connection = openConnection()) {
            connection.setAutoCommit(false);
            try {
                createHistoryTable(connection);
                int version = currentVersion(connection);
                if (version < 1) {
                    applyVersionOne(connection);
                    recordVersion(connection, 1, "initial dealership schema");
                }
                if (currentVersion(connection) != CURRENT_SCHEMA_VERSION) {
                    throw new IllegalStateException("unsupported schema version");
                }
                connection.commit();
            } catch (SQLException | RuntimeException exception) {
                connection.rollback();
                throw exception;
            }
        } catch (SQLException exception) {
            throw new IllegalStateException("database migration failed", exception);
        }
    }

    public int schemaVersion() {
        try (Connection connection = openConnection()) {
            createHistoryTable(connection);
            return currentVersion(connection);
        } catch (SQLException exception) {
            throw new IllegalStateException("could not read schema version", exception);
        }
    }

    private static void createHistoryTable(Connection connection) throws SQLException {
        execute(connection, "CREATE TABLE IF NOT EXISTS schema_history ("
                + "version INTEGER PRIMARY KEY, description VARCHAR(200) NOT NULL, "
                + "installed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)");
    }

    private static int currentVersion(Connection connection) throws SQLException {
        try (Statement statement = connection.createStatement();
                ResultSet result = statement.executeQuery("SELECT COALESCE(MAX(version), 0) FROM schema_history")) {
            result.next();
            return result.getInt(1);
        }
    }

    private static void recordVersion(Connection connection, int version, String description) throws SQLException {
        execute(connection, "INSERT INTO schema_history(version, description) VALUES (" + version + ", '"
                + description.replace("'", "''") + "')");
    }

    private static void applyVersionOne(Connection connection) throws SQLException {
        execute(connection, "CREATE TABLE accounts (username VARCHAR(100) PRIMARY KEY, "
                + "encoded_credential VARCHAR(500) NOT NULL, role VARCHAR(30) NOT NULL)");
        execute(connection, "CREATE TABLE inventory_listings (listing_id INTEGER PRIMARY KEY, "
                + "make VARCHAR(100) NOT NULL, model VARCHAR(100) NOT NULL, vehicle_year INTEGER NOT NULL, "
                + "price INTEGER NOT NULL CHECK (price >= 0), stock_quantity INTEGER NOT NULL CHECK (stock_quantity >= 0), "
                + "active BOOLEAN NOT NULL)");
        execute(connection, "CREATE TABLE purchase_requests (request_id INTEGER PRIMARY KEY, "
                + "listing_id INTEGER NOT NULL REFERENCES inventory_listings(listing_id), "
                + "customer_name VARCHAR(100) NOT NULL REFERENCES accounts(username), status VARCHAR(30) NOT NULL, "
                + "payment_months INTEGER NOT NULL DEFAULT 0, monthly_payment INTEGER NOT NULL DEFAULT 0)");
        execute(connection, "CREATE TABLE owned_vehicles (ownership_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "owner_username VARCHAR(100) NOT NULL REFERENCES accounts(username), make VARCHAR(100) NOT NULL, "
                + "model VARCHAR(100) NOT NULL, vehicle_year INTEGER NOT NULL)");
        execute(connection, "CREATE TABLE payment_plans (ownership_id INTEGER PRIMARY KEY REFERENCES owned_vehicles(ownership_id), "
                + "purchase_price INTEGER NOT NULL CHECK (purchase_price >= 0), payment_months INTEGER NOT NULL CHECK (payment_months > 0), "
                + "monthly_payment INTEGER NOT NULL CHECK (monthly_payment >= 0), amount_paid INTEGER NOT NULL DEFAULT 0, "
                + "balance INTEGER NOT NULL CHECK (balance >= 0))");
        execute(connection, "CREATE TABLE payment_transactions (transaction_id VARCHAR(40) PRIMARY KEY, "
                + "customer_name VARCHAR(100) NOT NULL REFERENCES accounts(username), amount INTEGER NOT NULL CHECK (amount > 0), "
                + "cumulative_paid INTEGER NOT NULL CHECK (cumulative_paid >= 0), resulting_balance INTEGER NOT NULL CHECK (resulting_balance >= 0), "
                + "recorded_at TIMESTAMP NOT NULL)");
        execute(connection, "CREATE INDEX idx_purchase_requests_listing ON purchase_requests(listing_id)");
        execute(connection, "CREATE INDEX idx_owned_vehicles_owner ON owned_vehicles(owner_username)");
        execute(connection, "CREATE INDEX idx_payment_transactions_customer ON payment_transactions(customer_name)");
    }

    private static void execute(Connection connection, String sql) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }

    private static String requireText(String value, String name) {
        String normalized = Objects.requireNonNull(value, name).trim();
        if (normalized.isEmpty()) throw new IllegalArgumentException(name + " must not be blank");
        return normalized;
    }
}
