from pathlib import Path
root=Path('modern')
p=root/'pom.xml'
s=p.read_text().replace('<version>1.0.17</version>','<version>1.0.18</version>',1)
p.write_text(s)
files={
'src/test/java/com/revature/project0/jdbc/JdbcIntegrationTestSupport.java': 'package com.revature.project0.jdbc;\n\nimport org.flywaydb.core.Flyway;\nimport org.junit.jupiter.api.Assumptions;\nimport javax.sql.DataSource;\nimport java.sql.*;\n\nabstract class JdbcIntegrationTestSupport {\n    DataSource dataSource(){\n        String url=System.getenv("PROJECT0_TEST_JDBC_URL");\n        Assumptions.assumeTrue(url!=null&&!url.isBlank(),"PROJECT0_TEST_JDBC_URL not configured");\n        return new DriverManagerDataSource(\n                url,\n                System.getenv("PROJECT0_TEST_JDBC_USER"),\n                System.getenv("PROJECT0_TEST_JDBC_PASSWORD"));\n    }\n\n    void migrate(DataSource ds){\n        Flyway.configure()\n                .dataSource(ds)\n                .load()\n                .migrate();\n    }\n\n    void clean(DataSource ds)throws Exception{\n        try(Connection c=ds.getConnection();Statement st=c.createStatement()){\n            st.execute("DELETE FROM outbox_event");\n            st.execute("DELETE FROM audit_event");\n            st.execute("DELETE FROM idempotency_record");\n            st.execute("DELETE FROM auth_session");\n            st.execute("DELETE FROM purchase");\n            st.execute("DELETE FROM offer");\n            st.execute("DELETE FROM vehicle");\n            st.execute("DELETE FROM app_user");\n        }\n    }\n}\n',
'src/test/java/com/revature/project0/jdbc/JdbcRepositoryIntegrationTest.java': 'package com.revature.project0.jdbc;\n\nimport com.revature.project0.domain.*;\nimport org.junit.jupiter.api.*;\nimport javax.sql.DataSource;\nimport java.math.BigDecimal;\nimport java.sql.Connection;\nimport static org.junit.jupiter.api.Assertions.*;\n\nclass JdbcRepositoryIntegrationTest extends JdbcIntegrationTestSupport {\n    @Test void repositoriesRoundTripDomainObjects() throws Exception {\n        DataSource ds=dataSource();migrate(ds);clean(ds);\n        try(Connection c=ds.getConnection()){\n            JdbcUserRepository users=new JdbcUserRepository(c);JdbcVehicleRepository vehicles=new JdbcVehicleRepository(c);JdbcOfferRepository offers=new JdbcOfferRepository(c);JdbcPurchaseRepository purchases=new JdbcPurchaseRepository(c);\n            User customer=users.save(User.create("customer","hash",Role.CUSTOMER));\n            Vehicle vehicle=vehicles.save(Vehicle.create("Honda","Civic",2020));\n            Offer offer=offers.save(Offer.create(customer.getId(),vehicle.getId(),new BigDecimal("18000.00")));\n            Purchase purchase=purchases.save(Purchase.create(customer.getId(),vehicle.getId(),offer.getId(),PaymentSchedule.of(new BigDecimal("18000.00"),36)));\n            assertEquals(customer.getId(),users.findByUsername("customer").orElseThrow().getId());\n            assertEquals(vehicle.getId(),vehicles.findById(vehicle.getId()).orElseThrow().getId());\n            assertEquals(offer.getId(),offers.findById(offer.getId()).orElseThrow().getId());\n            assertEquals(new BigDecimal("500.00"),purchases.findById(purchase.getId()).orElseThrow().getSchedule().getMonthlyPayment());\n        }\n    }\n}\n',
'src/test/java/com/revature/project0/jdbc/TransactionalOfferServiceIntegrationTest.java': 'package com.revature.project0.jdbc;\n\nimport com.revature.project0.domain.*;\nimport org.junit.jupiter.api.*;\nimport javax.sql.DataSource;\nimport java.math.BigDecimal;\nimport java.sql.Connection;\nimport static org.junit.jupiter.api.Assertions.*;\n\nclass TransactionalOfferServiceIntegrationTest extends JdbcIntegrationTestSupport {\n    @Test void acceptanceIsCommittedAsOneDatabaseTransaction() throws Exception {\n        DataSource ds=dataSource();migrate(ds);clean(ds);\n        User customer1,customer2,employee;Vehicle vehicle;Offer first,second;\n        try(Connection c=ds.getConnection()){\n            JdbcUserRepository users=new JdbcUserRepository(c);JdbcVehicleRepository vehicles=new JdbcVehicleRepository(c);JdbcOfferRepository offers=new JdbcOfferRepository(c);\n            customer1=users.save(User.create("c1","h",Role.CUSTOMER));customer2=users.save(User.create("c2","h",Role.CUSTOMER));employee=users.save(User.create("e1","h",Role.EMPLOYEE));vehicle=vehicles.save(Vehicle.create("Honda","Accord",2021));first=offers.save(Offer.create(customer1.getId(),vehicle.getId(),new BigDecimal("18000.00")));second=offers.save(Offer.create(customer2.getId(),vehicle.getId(),new BigDecimal("17500.00")));\n        }\n        Purchase purchase=new TransactionalOfferService(ds).acceptOffer(employee.getId(),first.getId(),36);\n        try(Connection c=ds.getConnection()){\n            assertEquals(OfferStatus.ACCEPTED,new JdbcOfferRepository(c).findById(first.getId()).orElseThrow().getStatus());\n            assertEquals(OfferStatus.REJECTED,new JdbcOfferRepository(c).findById(second.getId()).orElseThrow().getStatus());\n            assertFalse(new JdbcVehicleRepository(c).findById(vehicle.getId()).orElseThrow().isAvailable());\n            assertEquals(purchase.getId(),new JdbcPurchaseRepository(c).findById(purchase.getId()).orElseThrow().getId());\n        }\n    }\n}\n',
}
for rel,content in files.items():
    p=root/rel
    p.write_text(content)
print('V1_0_18_PATCH_APPLIED')
